name: flutter_sim_country_code_example
description: Demonstrates how to use the flutter_sim_country_code plugin.
publish_to: 'none'

environment:
  flutter: ^3.24.4
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:

  flutter_sim_country_code:
    path: ../

flutter:
  uses-material-design: true

