name: flutter_sim_country_code
description: Flutter sim country code
version: 0.1.2
homepage: https://github.com/derTuca/flutter_sim_country_code

environment:
  flutter: ^3.24.4
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android: 
        package: com.example.flutter_sim_country_code
        pluginClass: FlutterSimCountryCodePlugin
      ios:
        pluginClass: FlutterSimCountryCodePlugin